module.exports = {
  "@blue-6": "#353FE5",
  "@primary-color": "#00cd71",
  "@success-color": "#00cd71",
  "@error-color": "#fc4a1a",
  "@highlight-color": "#fc4a1a",
  "@warning-color": "#fc4a1a",
  "@normal-color": "#f8f8f8",
  "@black": "#15242d",
  "@body-background": "#fdfdfd",
  "@component-background": "#fdfdfd",
  "@text-color": "#15242d",
  "@text-color-secondary": "#6c757d",
  "@text-color-dark": "#15242d",
  "@font-family": "Roboto, sans-serif",
  "@font-size-base": "16px",
  "@font-size-lg": "@font-size-base + 4px",
  "@font-size-sm": "@font-size-base - 2px",
  "@heading-1-size": "72px",
  "@heading-2-size": "56px",
  "@heading-3-size": "32px",
  "@heading-4-size": "28px",
  "@heading-5-size": "24px",
  "@heading-6-size": "18px",
  "@typography-title-font-weight": "700",
  "@typography-title-margin-bottom": "20px",
  "@line-height-base": "1.3",
  "@border-radius-base": "10px",
  "@border-radius-sm": "5px",
  "@height-base": "35px",
  "@height-lg": "55px",
  "@height-sm": "35px",
  "@divider-color": "#EBEFF2",
  "@link-color": "#15242d",
  "@link-hover-color": "rgba(21, 36, 45, 0.7)",
  "@link-active-color": "#15242d",
  "@border-color-base": "#6c757d",
  "@disabled-bg": "#d6d6d6",
  "@btn-font-weight": "600",
  "@btn-border-radius-sm": "@border-radius-sm",
  "@btn-shadow": "0px 4px 8px rgba(0, 205, 113, 0.3)",
  "@btn-primary-shadow": "0px 4px 8px rgba(0, 205, 113, 0.3)",
  "@btn-font-size-lg": "20px",
  "@btn-font-size-sm": "17px",
  "@btn-line-height": "1",
  "@btn-padding-horizontal-base": "25px",
  "@btn-padding-horizontal-lg": "55px",
  "@btn-padding-horizontal-sm": "25px",
  "@grid-columns": "12",
  // form
  "@input-height-base": "45px",
  "@input-height-lg": "55px",
  "@input-color": "#15242D",
  "@input-icon-color": "#6C757D",
  "@input-border-color": "#6C757D",
  "@label-color": "#15242D",
  "@form-item-label-font-size": "16px",
  "@checkbox-size": "24px",
  "@checkbox-border-width": "2px",
  // table
  "@table-header-bg": "#F8F8F8",
  "@table-header-color": "#15242D",
  "@table-row-hover-bg": "#F8F8F8",
  "@table-border-radius-base": "0",
  // modal
  "@modal-header-padding": "30px 30px 15px 30px",
  "@modal-header-border-width": "1px",
  "@modal-header-title-font-size": "28px",
  "@modal-close-color": "#6C757D",
  "@modal-body-padding": "20px 30px 30px 30px",
  "@modal-mask-bg": "rgba(21,36,45, 0.5)",
  // select
  "@select-border-color": "#EBEFF2",
  "@select-item-selected-color": "#6C757D",
  "@select-item-selected-font-weight": "300",
  "@select-item-selected-bg": "#F8F8F8",
  "@select-item-active-bg": "#F8F8F8",
  "@select-dropdown-vertical-padding": "4px",
  "@select-dropdown-font-size": "16px",
  "@select-selection-item-bg": "#F8F8F8",
  // card
  "@card-skeleton-bg": "#F8F8F8",
  "@card-padding-base": "30px",
  "@card-padding-base-sm": "24px",
  "@card-shadow":
    "0px 16px 24px rgba(0, 0, 0, 0.06), 0px 2px 6px rgba(0, 0, 0, 0.04), 0px 0px 1px rgba(0, 0, 0, 0.04)",
  // tag
  "@tag-default-bg": "rgba(108,117,125, 0.1)",
  "@tag-default-color": "#6C757D",
  "@tag-font-size": "14px",
  "@tag-line-height": "20px",
  // tooltip
  "@tooltip-color": "#6C757D",
  "@tooltip-bg": "#ffffff",
  // progress
  "@progress-default-color": "#F8F8F8",
  "@progress-radius": "5px",
  // media
  "@sm": "575.98px",
  "@md": "767.98px",
  "@lg": "991.98px",
  "@xl": "1199.98px",
  "@osx": "1439.98px",
  "@xxl": "1599.98px",
};
